### ISSUE TITLE
script python para baixar bases de dados da redehumaniza no facebook e etc...

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#101]
@leogermani Leo acessei este link: http://nocodewebscraping.com/facebook-scraper/
e fiz o processo para estes 2 aplicar estes 2 scripts:
https://drive.google.com/file/d/0Bw1LIIbSl0xuRTNCZElUa3U1b1U/view
e
https://drive.google.com/file/d/0Bw1LIIbSl0xuYkFseUgtWWRIbDg/view
antes ele ajuda a conseguir um código definitivo para exportar dados do face. no tutoria ele explica.

extrai para esta planilha:
https://docs.google.com/spreadsheets/d/1KV9ogye-SZaLwOSDcfYCFcowAxO44YZ15R4FUznPKTc/edit?usp=sharing

no meu computador windows, utilizando o powershell, dei o seguinte comando:
![image](https://user-images.githubusercontent.com/28462167/28735653-95b59cf4-73bc-11e7-9c50-a82cfd9a41a5.png)
e como vc pode ver ele me pede o nome da pagina no facebook, e não a url, ate ai tudo bem, posso substituir com facilidade.

vc pode me ajudar a saber que comando eu daria para o powershell aplicar o arquivo posts.py a uma planilha em csv com nomes das fan pages?

no caso da raspagem de uma unica pagina do face fiz desta forma aqui:
criei a pasta raspagem no meu desktop, com os arquivos do script dentro ( posts.py )
abri o powershell e dei enter
digitei python, enter
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
PS C:\Users\mariana> cd desktop
PS C:\Users\mariana\desktop> cd raspagem
PS C:\Users\mariana\desktop\raspagem> python posts.py
Please Paste Public Page Name:institutounibanco
Please Paste Your Access Token:193485244522621|bbad2a8ab2baca4fc2c7d2b06c2822a3
e ele iniciou o processo:
Scraping institutounibanco Facebook Page: 2017-07-26 17:10:02.148000

criou um csv na pasta raspagem com os dados,

pode me ajudar a fazer isso para 3000 páginas, criando um único csv?
tenho um csv com a lista das url, mas posso limpar e colocar só o nome da página.

valeu!

bjs

Mariana

**Comment by leogermani** [comment]
Posso ajudar. Quando vc voltar de ferias?

Quando eu falei pra vc botar no github, quis dizer criar um repositorio com o seu script ;) posso fazer uma oficininha com vc disso

**Comment by MarianaSalles** [comment]
pode!

eu tentei achar o melhor lugar.
realmente não consegui!

Vale a oficina tb!

bjus

Em 28 de julho de 2017 18:07, leogermani <notifications@github.com>
escreveu:
