### ISSUE TITLE
Encerramento de conta

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#102]
Na edição de perfil, acrescentar opção para usuário poder encerrar a própria conta.

Neste caso, precisamos pensar o que fazer com seus posts...

Idealmente, haveria uma opção para a pessoa fazer download de todo o conteúdo que ela publicou na rede

**Comment by MarianaSalles** [comment]
vale aqui perguntar se ele quer deixar seu conteúdo para o usuário legado RHS, que mantem ativo os posts de quem se descadastra na rede. ou quer apagar tudo. ;-(

**Comment by MarianaSalles** [comment]
Isso ficou espetacular. testei agora no migração, usando uma das contas spam.  nao deu pra testar o legado, mas podemos fazer ja na rhs oficial.
