### ISSUE TITLE
Na página de publicar post, ao editar um post existente, não está exibindo as categorias do post

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#112]

**Comment by leogermani** [comment]
Pra reproduzir,

Entre com um usuário qualquer.

Clique em Publicar post

Crie e publique um POST

você vai ver q é obrigatório selecionar pelo menos uma categoria

Vá em Minhas publicações

Clique em editar esse post 

Vai abrir a mesma tela q vc usou pra criar o post

Repare que a categoria não tá preenchida

(nota: tanto a criação quanto a edição é naquele tela no front end, e não no admin do WP. Melhor testar com um usuário não admin)

**Comment by Weryques** [comment]
O erro também se reproduz nas Tags.
