### ISSUE TITLE
Admin para fila de votação

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#13]
Página no admin com as seguintes opções:

. Texo introdutorio da fila de votação

. Número de dias q posts podem ser votados (select)

. Número de votos para aprovação (select)

**Comment by leogermani** [comment]
- [x] Fazer o número de dias e a qtde de votos serem um SELECT, pra escolher um número... pode ser tipo de 1 a 50

- [x] Remover aquele item do menu inutil, RHS Menu

- [x] Trocar "Descrição" por "Texto introdutório"

- [x] Fazer um valor padrão para a qtde de votos e num de dias. Se não tiver nada setado no admin, já considerar alguma coisa (e deixar isso escrito na tela de admin. Valor padrão: x)

**Comment by willavelar** [comment]
Coloquei o menu nas Configurações, porque o wordpress só coloca sub-menu com 2 itens.

**Comment by leogermani** [comment]
Ao recuperar as opções salvas, tá vindo o valor trocado. votos no lugar de dias.

Não tem como eu mudar o texto sem mudar as outras opções. Ou seja, quero deixar elas no padrão, mas quero mudar o texto...

Ou coloca uma opção vazia antes do 1 (com o label padrão), tipo isso:

`<option value="" <?php echo $value == '' ? 'selected' : ''; ?> >Padrão (<?php echo $default; ?>)</option>`

ou faz com que o select já venha selecionado na opção padrão (acho essa solução melhor)

- [x] Fazer o texto definido no admin aparecer na tela lá no lugar do texto introdutório

**Comment by leogermani** [comment]
@willavelar dá uma olhada no meu último commit relacionado a essa issue. Ficou melhor assim.
