### ISSUE TITLE
Conferir URLs antigas

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#146]
Conferir URLs do site antigo e ver se vão funcionar direitinho na url nova para manter estatísticas

**Comment by fabianobn** [comment]
As comunidades na http://www.rredehumanizasus.net é chamada como grupos

A lista de Membros das comunidades é através do endereço: http://www.rredehumanizasus.net/node/_ID_/members

O endereço http://www.redehumanizasus.net/comunidades retorna uma listagem de videos

Ao acessar um video na listagem que foi pego nas comunidades na plataforma em drupal e pegar o link e testar no wordpress o mesmo retornou NOT FounD.

O post a seguir retornou not found (Não veio no banco de dados pego do drupal ou não migrou do drupal para o wordpress... Verificar): 96608-fisioterapia-na-atencao-basica-roda-de-gestante

O link de tags e category está retornando not found ao pegar do drupal e passar para o wordpress. Exemplos:

http://migracao.redehumanizasus.net/category/tags/odontologia-coletiva
http://migracao.redehumanizasus.net/tags/saude-coletiva

**Comment by leogermani** [comment]
Adicionado suporte as URLS no padrão antigo para tags e comunidades

os vídeos presentes em /comunidades no site drupal não estão sendo importados por hora

**Comment by r-guimaraes** [comment]
Conferir estrutura: http://redehumanizasus.net/node/96282

(5995ccf370f37d1478da45c711fb185de7d688f3)

**Comment by MarianaSalles** [comment]
Leo tenho visto algumas descontinuidades em post bem importantes no analytycs. Podemos olhar novamente para esse quesito aqui? olha um exemplo aqui: 
https://analytics.google.com/analytics/web/?hl=pt-BR&pli=1#report/content-pages/a4336151w8351486p8696380/%3F_u.date00%3D20080117%26_u.date01%3D20180117%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.pagePath%3A%2F6804-o-susontem-e-hoje/

**Comment by MarianaSalles** [comment]
alguns link começam em set de 2017 e outros pararam de serem seguidos na mesma data da migração de sistema.  Vamos olhar de novo para isso? bjs

**Comment by leogermani** [comment]
Mari, curioso pq esse link de exemplo q vc mandou segue funcionando normalmente, veja: http://redehumanizasus.net/6804-o-susontem-e-hoje/

**Comment by MarianaSalles** [comment]
sim justamente, o link em si esta  ok, mas o analytycs parou  de segui-lo.  Minha questão é mais perder a serie histórica do acesso a ele.  enfim, vc tem alguma idéia porque o analytics parou  de computar visitas e esse link?

**Comment by pedronaves** [comment]
@MarianaSalles descobri o problema com o rastreamento, a página onde o rastreamento cessa não tem o "/" no final. 

Acredito que houve alguma modificação nas URL's e ele passou então a coletar dados com o "/", aqui segue os dados coletados: https://analytics.google.com/analytics/web/?hl=pt-BR&pli=1#report/content-pages/a4336151w8351486p8696380/%3F_u.date00%3D20080117%26_u.date01%3D20180117%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.pagePath%3A%2F6804-o-susontem-e-hoje%2F%26_r.tabId%3Dnavigationsummary%26explorer-graphOptions.clearCompareConcept%3Dtrue%26explorer-graphMode.mode%3DmotionChart/

Se você acessar o link: http://redehumanizasus.net/6804-o-susontem-e-hoje/

E em seguida acessar: https://analytics.google.com/analytics/web/#realtime/rt-content/a4336151w8351486p8696380/%3Ffilter.list%3D10%3D%3D%25252F6804-o-susontem-e-hoje%25252F%3B/

Você irá conseguir ver que ele está rastreando

**Comment by leogermani** [comment]
Boa! Mistério resolvido!

Será que não tem como no Google Analytics mesmo resolver isso?

5 segundo de busca: vale uma pesquisa maior: https://www.getelevar.com/how-to/fix-duplicate-url-google-analytics/

**Comment by MarianaSalles** [comment]
Boa Pedro!
Isso ai está me preocupando muito!
Agora temos a trilha para resolver.
como juntar a url antiga com a url com (/)?
Mudando o fim da url de novo?
Leo deu dicas abaixo.
Valeu por abrir esse rastro. Bora achar essa solução.
;-)


Mariana

Em 8 de fevereiro de 2018 11:06, Pedro Naves <notifications@github.com>
escreveu:

**Comment by pedronaves** [comment]
@MarianaSalles , tem como me dar acesso para editar os filtros? O nível de usuário que eu estou lá eu não consigo alterar para realizar os testes

**Comment by MarianaSalles** [comment]
claro.

Em 2 de março de 2018 10:06, Pedro Naves <notifications@github.com>
escreveu:

**Comment by pedronaves** [comment]
Mari, criei um filtro que agora remove a "/" do final da url no Analytics,

**Comment by MarianaSalles** [comment]
Maravilha Pedro.
Nossa que alivio!
que ótima notícia.
boa!

bjs,

Mari

2018-03-09 15:24 GMT-03:00 Pedro Naves <notifications@github.com>:
