### ISSUE TITLE
Criar endpoint customizado para usuários

### ISSUE THREAD

**Issue by mateuswetah** [medialab-ufg/wp-rhs#151]
Como a API só lista autores, precisamos de uma versão customizada da endpoint /users/<id> para que o aplictivo possa exibir dados de usuários que ainda não publicaram nenhum post. Isto pode ser feito em uma API customizada ou talvez buscando modificar as configurações de permissões da endpoint atual, precisamos descobrir qual a melhor estratégia...

**Comment by pedronaves** [comment]
o endereço do endpoint ficou:
/wp-json/rhs/v1/user/ID_USUARIO

**Comment by mateuswetah** [comment]
Precisamos também da listagem no endpoint, para que posssamos fazer consultas como `/wp-json/rhs/v1/user?include=ID1,ID2,ID3&page=2`

**Comment by pedronaves** [comment]
endpoint criado, endereço ficou
~~~html
public/wp-json/rhs/v1/user/include=ID2,ID2&page=N&per_page=N
~~~

foi necessário criar um parâmetro para número de resultados por página

**Comment by mateuswetah** [comment]
Acho que precisamos  manter o padrão dos resultados. Por exemplo, na consulta user/<ID>, o campo "id" está minúsculo, enquanto na listagem de user/inclucude... O campo está maiúsculo ("ID"). Também não está vindo na listagem o "avatar_urls", que são necessários para mostrar os usuários da lista do app. Já campos como o "user_pass" são dados sensíveis, mesmo que em hash, portanto não precisaria ser exposto.
