### ISSUE TITLE
Compartilhamento em redes sociais

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#17]
compartilhar em várias redes (definir) e salvar estatísticas de compartilhamento

Importar as estatísticas de compartilhamento atuais

**Comment by fabianobn** [comment]
- [x] - Botões de compartilhamentos e curtida seram icones.
-[ ] - 
[
Estatisticas de Curtidas e Compartilhamentos -> Pesquisar Plugins!
Plugin com botão compartilhar e curtir Facebook com estatisticas.
]

- [x] - Mudar o compartilhar no card para estatisticas.

- [ ] - Adicionar Meta dados de compartilhamento.
