### ISSUE TITLE
Ao responder formulário de contato, enviar email

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#170]
Email para quem enviou a mensagem original, seja usuário logado ou não logado

**Comment by pedronaves** [comment]
Fluxos

Usuário Logado
1 - usuário preenche contato
2 - responsável pelo departamento recebe notificação com link para o histórico do contato
3 - usuário recebe notificação de contato, na notificação é possível acessar o histórico do contato

Usuário não Logado
1 - usuário preenche contato
2 - responsável pelo departamento recebe notificação com link para o histórico do contato
