### ISSUE TITLE
Permitir que usuários apaguem o próprio post

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#181]
Na listagem de Minhas Publicações e na de edição de post, colocar um botão para Apagar post.

Esses posts vão pra lixeira, e na listagem em "Minhas Publicações" aparecem com esse status

**Comment by Weryques** [comment]
Decidiu-se que seria mais adequado ter o botão de apagar post apenas na listagem de Minhas Publicações.

**Comment by MarianaSalles** [comment]
ok. Por mim validado. ;-)
