### ISSUE TITLE
Tratamento de Tags

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#189]
- [x] pesquisar se existem um plugin poderoso pra WP para gerenciar Tags

- [ ] script para tratar tags, em cima da planilha da Mari e normalizando (minúsculas, sem #)

- [ ] aplicar filtro na hora de inserir da tag, para normalizar minuscula, sem #

- [ ] normalizar quando for buscar

**Comment by r-guimaraes** [comment]
Realizar testes iniciais com o plugin Term Management Tools (já ativado no Homolog)
