### ISSUE TITLE
Indicar post

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#192]
Fazer esquema de indicar post para outro usuário

um autocomplete que escolhe um ou mais usuários e aí envia uma notificação para esses usuários

**Comment by MarianaSalles** [comment]
muito legal. bora implementar e testar com o uso. ja testei na migração. muito bom. Não recebi o email porque acho que na migração não completa a tarefa certo? E indica um de cada vez ne? 
bora implementar e vemos no uso como se comporta.

**Comment by MarianaSalles** [comment]
Pedro tudo bem/ Vc pode dar uma olhada novamente neste tópico. Tentamos indicar posts e alguns nomes não aparecem na lista. Se vc testar Ricardo Teixeira por exemplo, não aparece. O que pode ser? Acho que ele está listando apenas uma parte? se quiser podemos falar para eu te dar mais detalhes. abs, Mariana

**Comment by r-guimaraes** [comment]
Voltamos pra Progresso pra terminar mais alguns detalhes

**Comment by MarianaSalles** [comment]
Rodrigo este tb já foi né? tem aprimoramento mas já esta em outras issues. Vamos levar para a coluna feito? ;-)
