### ISSUE TITLE
Sala de eventos

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#193]
Transmissão ao vivo do youtube Live com chat

**Comment by r-guimaraes** [comment]
Passando o card para Validation até definirmos se a solução atual atende, ou é necessário implementar o chat. Em paralelo, pesquisando soluções alternativas

**Comment by r-guimaraes** [comment]
http://migracao.redehumanizasus.net/evento

**Comment by leogermani** [comment]
Como usar: https://github.com/medialab-ufg/wp-rhs/blob/develop/docs/events.md

**Comment by MarianaSalles** [comment]
pergunta: podemo embedar outros videos que não do youtube? 
digo isso porque na transmissão prevista para dia 27, é um embedar de outro sistema. se nao for, será que consigo transmitir minha tela do computador no nosso canal do youtibe? ai resolve, porque gero um link por la.

**Comment by leogermani** [comment]
@MarianaSalles se tiver previsto podemos fazer tudo. Do jeito que foi feito é só vídeo de transmissão do youtube.

Passa pra gente direitinho os detalhes desse próximo evento que a gente vê se é possível.
