### ISSUE TITLE
implementar exportação de dados feitos na barra de pesquisa de post e usuários (xml e csv)

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#195]

**Comment by pedronaves** [comment]
Olá Mari, bom dia, existe um formato ou layout a ser seguido?
E quais dados devem conter em cada exportação?

**Comment by MarianaSalles** [comment]
Pedro,

acho que não precisamos do layout.
O Ideal é que exporte uma planilha em csv, ou xml.

minha sugestão é que neste planilha conste os dados em colunas:

*Postagens:*
data do post
nome do perfil que postou
link do post
numero de visualizações
numero de compartilhamentos
numero de votos
número de comentários
estado do assunto do post
cidade do assunto do post

*Usuários*
nome do usuário
data de cadastro
numero total de postagens
numero total de votos recebidos em postagens
estado do usuário
cidade do usuário

vc vê alguma outra possibilidade?

o que *não* pode contar: email do usuário.

abs,

mariana


2017-09-25 9:19 GMT-03:00 Pedro Naves <notifications@github.com>:

**Comment by r-guimaraes** [comment]
- [x] Adaptar nome do arquivo gerado contendo indicação (post ou usuário), e número da página exportada

- [x] Caso seja adicionado o conteúdo do post na exportação, o mesmo deve trazer apenas texto, e remover quaisquer tags HTML

- [x] Se conteúdo não precisar ser exportado, aumentar e testar timeout limite de cada arquivo, passando de 100 para 500 itens

**Comment by r-guimaraes** [comment]
Seria bom informar no modal quantos registros são inclusos em cada arquivo para download

**Comment by r-guimaraes** [comment]
@pedronaves Massa!

**Comment by MarianaSalles** [comment]
Pedro estamos na vib para ver isso rolar! Essa ação na Rede é uma das issues mais importantes junto do lançamento do acervo e mobile. Os pesquisadores estão babando nisso para poder fazer parte dos bancos que querem avaliar. Da noticias! ;-)

**Comment by pedronaves** [comment]
Mari, finalizamos ontem, agora vai passar pela validação, o @r-guimaraes já está ciente e providenciando subir para produção.

**Comment by MarianaSalles** [comment]
Valeu Pedro!
Vou la experimentar!
;-)

2018-01-22 13:54 GMT-02:00 Pedro Naves <notifications@github.com>:

**Comment by MarianaSalles** [comment]
exportei a pesquisa de usuários, veio bem legal, seria bom incluir numero de comentários em posts.  mas abri e ficou tudo bem organizado. ;-) 
Fiz a pesquisa sobre postagens do Ceará, ficou muito bom o aviso com o numero das paginas para baixar, intuitivo, e organizado, fácil de sacar o uso., pelo menos para mim. Mas o arquivo já veio bem confuso, não consegui organiza-lo em colunas, não entendi as variáveis selecionadas. e tb a opção ou não de exportar com o conteúdo ou não.  Como foi a experiência para vcs? Conseguiram organizar bem o conteúdo do csv?  quais variáveis estão disponíveis? 
Pode ser que eu tenha aberto no excel e ao separar pelo marcador (,) tenha feito um caminho, ruim, mas na pesquisa de usuários isso foi bem fácil. por isso estranhei.

**Comment by MarianaSalles** [comment]
Pedro e Rodrigo, exportei agora e abri então no google planilhas, realmente ali ele fica lindão. Alegria total.  Dali tb fica fácil fusionar as planilhas. muito bom! parabéns pelo trabalho.  Vale  apenas avaliar a entrada do índice de comentários nos usuários, isso ajuda a saber quem de fato consegue promover uma rede de conversações na rhs. Indicador importante para os usuários.  no mais boar colocar isso na rua, apresentar para os pesquisadores e  deixar funcionar esta nova entrega! isso vai abrir muitas novas possibilidades.  Sei que vcs trabalharam tb na API da rede, mas essa interface amigável ajuda muito ao usuário comum. com isso testado  no uso pela pesquisa posso fazer uma entrega para labs universitários voltado a pesquisas em saúde coletiva e ampliar o estudo da rede! valeu!  Sobe isso minha gente! não nos matem de ansiedade! bjs

**Comment by pedronaves** [comment]
Oin Mari, fizemos todos testes aqui do CSV pra abrir corretamente no Excel, e de fato ele foi o único que se comportou de maneira estranha :(
no Libreoffice, Google Docs e Numbers (Mac), abriu certinho.
Falei com o Rodrigo e estou trabalhando em uma solução para exportar um XLS, específico. O que você acha?
E fico muito feliz que essa nova feature irá auxiliar os usuários.
Vou inserir também a quantidade de comentários de determinado usuário.
Pra subir agora só estávamos dependendo da sua validação <3

**Comment by MarianaSalles** [comment]
Blz Pedro.
eu tive problemas tb com exportações de csv via raspagem na web com scripts
do phyton, mas que exatamente como vc reportou, abriam bem no google docs e
outros.
Como a exportação do usuários tava bonitinha, achei que o problema podia
ser outro.
que bom que não!

Vale agora apenas inserir o numero total de comentários em postagens na
exportação dos usuários e publicar!
Já esta mais do que bom para o que vamos usar!

quando ativarmos a comunidade de pesquisa mais ampla, podemos ajustar isso.

valeu! muito bom! Vai realmente ajudar muito!

bjs,
Mari



Em 23 de janeiro de 2018 16:02, Pedro Naves <notifications@github.com>
escreveu:

**Comment by MarianaSalles** [comment]
Rodrigo e Pedro, testei agora a exportação em  XLS, ficou ótima. ta muito legal, acho que podemos fazer tb um lançamento disso. como o acervo. lançar a própria rede como um acervo em si. e esse novo acesso a ela. quero selecionar 3 ou 4 labs de saúde coletiva para levar essa oferta de dados e ver se fazemos parcerias de pesquisa.  Vou amadurecer isso com Dalton e Ricardo, e dai damos a devida visibilidade para essa nova feature da rede. muito bom, mais uma excelente conquista para a RHS. bjs
