### ISSUE TITLE
implementar quadrinho de resumo do total de itens recuperados na pesquisa (post/usuários)

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#196]
a ideia é dar noção do tamanho geral dos itens recuperados no resultado de pesquisa sobre post e usuários.

**Comment by pedronaves** [comment]
deverá será exibido o total dos resultados?

por exemplo:
Quantidade de Resultados: 92

ou será necessário exibir mais contagens de acordo com os filtros?

**Comment by pedronaves** [comment]
@fabianobn precisamos das suas habilidades para achar o lugar ideal pra contagem :)

**Comment by MarianaSalles** [comment]
Oi Pedro, tudo bem?

Acho que por ora podemos fazer o resultado total de itens recuperados.
Quando aplica o filtro ele tb altera o número, correto?
Mas poderia ser um número total de itens listados, o que vai tb dar
notícias sobre o tamanho da pesquisa para baixar num xml, ou csv.

veja a sugestão abaixo:

[image: Imagem inline 1]

o que vc acha?


Em 22 de setembro de 2017 16:07, Pedro Naves <notifications@github.com>
escreveu:

**Comment by pedronaves** [comment]
Tudo bem e contigo Mari?
Justamente, ao aplicar o filtro a contagem de resultados é atualizada.

Você consegue me novamente a sugestão? Ela não veio anexada :(

**Comment by fabianobn** [comment]
Blz @pedronaves  vamos la!!! Estarei dando uma estudado do layout e de como podemos exibir ^^

**Comment by MarianaSalles** [comment]
Consigo sim. ai vai!

abs,

Mariana

Em 25 de setembro de 2017 08:27, Pedro Naves <notifications@github.com>
escreveu:

**Comment by pedronaves** [comment]
[Uploading rhs pesquisa.png...]

**Comment by pedronaves** [comment]
![rhs pesquisa.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598af6f2fb1a7b11ef52853d/125516c66e82c728ace21e0d46fa9c89639286ba9efcb650a51fbcd6395428792c07b7692ac7b671ef402950095d47ab470a5742fcf98d2ef3b23972de5419f1c32f0e2a92624cf5f2d75dad0ba821834584b3bc8c4bc0e03920e08a8e472c53.png)

**Comment by MarianaSalles** [comment]
acho que está ok. Quando incluir o ícone de download podemos fechar um design definitivo. o que vc acham?
