### ISSUE TITLE
Estudar configurações das notificações

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#198]
https://documentation.onesignal.com/reference#create-notification

Olhar na documentação do OneSignal os parametros de criação de notificação e experimentar o que serve pra gente.

Imagem, link, prioridade, agrupamento, etc...

**Comment by pedronaves** [comment]
**Agrupamento**

Ação | android_group
----- | --------------- 
Comentário no post | rhs_comments_in_post
Novo Post na Comunidade | rhs_new_community_post
Novo Post de Usuário | rhs_new_post_from_user
Novo Post sendo Seguido | rhs_post_followed
Contato respondido | rhs_replied_ticket
Usuário sendo Seguido| rhs_user_follow_author


*Botões*

Ação | id | text
----- | -- | ----
Comentário no post | open_comments_in_post | Ver Comentário
Comentário no post | open_user_comments_in_post | Ver Usuário
Novo Post de Usuário | open_post_new_post_from_user | Ver Post
Novo Post de Usuário | open_user_new_post_from_user | Ver Usuário
Novo Post sendo Seguido | open_post_followed | Ver Post
Novo Post sendo Seguido | open_user_post_followed | Ver Usuário
Contato respondido | open_replied_ticket | Ver Resposta
Usuário sendo Seguido | open_user_follow_author | Ver Usuário
Post Promovido | open_post_promoted | Ver Post

**Comment by mateuswetah** [comment]
Testando:
[x] open_comments_in_post (Encontrados problemas relacionados à Ref. #202)
[x] open_user_comments_in_post 
[x] open_post_new_post_from_user
[x] open_user_new_post_from_user
[x] open_post_followed
[x] open_user_post_followed
[ ] open_replied_ticket
[x] open_user_follow_author
[ ] open_post_promoted

**Comment by pedronaves** [comment]
[ x ]

**Comment by pedronaves** [comment]
- [x]

**Comment by pedronaves** [comment]
@leogermani @mateuswetah nessa mesma issue já vamos implementar as configurações para iOS também?
