### ISSUE TITLE
WP-JSON: Fila de votação não funcionando.

### ISSUE THREAD

**Issue by mateuswetah** [medialab-ufg/wp-rhs#202]
A filtragem por status=voting-queue no enpoint de Posts só funciona com posts publicados pelo próprio autor autenticado. Deveria retornar todos os posts com esse status.

**Comment by mateuswetah** [comment]
Confirmado bug provavelmente relacionado à isso também:

A consulta por /comments/ retorna 401, unauthorized, caso o comentário tenha sido postado em um post que está na fila de votação, mesmo caso o usuário seeja o dono do post :/

**Comment by mateuswetah** [comment]
Infelizmente ainda tem treta :(

Quanto fazemos requisições para a endpoint de posts passando o status="voting-queue", e junto passo a query _embed="true" (necessária para que, ao invés de somente o id do autor, venha o também o objeto autor), essa requisição interna retorna 403 (rest_user_cannot_view), "Sem permissão para listar usuários".

**Comment by leogermani** [comment]
O erro acontece quando o autor do post que está na fila ainda não tem nenhum post publicado. nesse caso um usuário comum não tem permissão para ver seus detalhes
