### ISSUE TITLE
No admin: Listagem de post - filtrar posts que estão no carrossel

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#205]

**Comment by leogermani** [comment]
boa!

duas coisinhas

1. coloca isso na classe do carousel, não na classe dos posts

2. muda o nome filter-by para alguma coisa menos generica, como filter-by-carousel, ou ainda, rhs-filter-carousel

**Comment by pedronaves** [comment]
Certo, alterado.
Tinha pensado em deixar esse filtro com nome genérico para poder aproveitar no futuro pra outros tipos de filtros, se necessário. A priori alterei ele pra rhs-filter-carousel.
