### ISSUE TITLE
Label na busca de usuários

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#206]
O label Palavra-chave hoje busca apenas em poucos campos. Aparentemnte só nome ou nome e email

Se for isso, mudar o label de "palavra chave" para "Nome ou email"

mas pra isso precisa verificar em quais campos esse keyword busca exatamente

**Comment by pedronaves** [comment]
A string de busca tem algumas 'mágicas'. O comportamento default de search_columns é:
user_email se @ está presente.
user_login e ID se a busca for numérica
user_url se a busca contém http:// ou https://
ou ... user_login e user_nicename se há uma string
Esses defaults são setados caso não haja nenhum argumento em search_columns
