### ISSUE TITLE
Fluxo ao receber push notification

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#210]
Pra mim tá assim:

O app está completamente fechado.

Recebo uma notificação.

clico na notificação

o app abre e vai pra tela de noiciações

a tela está vazia (não há notificações)

eu puxo pra baixo pra recarregar e as notificações aparecem certinho

**Comment by mateuswetah** [comment]
Isso era um erro de autenticaçao, foi resolvido. No proximo commit (do rhs-app) estara ok.
