### ISSUE TITLE
Ordenação do widget de participantes

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#211]
Não está ordenando corretamente por último login

**Comment by MarianaSalles** [comment]
tb vi isso. continua  pela ordem alfabética do email.

**Comment by MarianaSalles** [comment]
mas só quado os filtros não estão aplicados. quando fiz uma pesquisa de usuários por estado, o resultado sim aparece em ordem alfabética pelo nome.

**Comment by leogermani** [comment]
Mari, essa issue se refere aquele Widget de "Participantes" da barra lateral, e não a página de busca.
