### ISSUE TITLE
Problema ao exibir fotos de usuarios e posts nas notificações

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#212]
Não está exibindo corretamente.

Posts estão quebrados e usuários estão sem avatar mesmo em casos que tem avatrr

**Comment by MarianaSalles** [comment]
não consegui testar. no meu user no migração.rhs esta sem nenhuma notificação no histórico. mas se vc testaram e esta ok, maravilha, feito!
