### ISSUE TITLE
Relatorio de estatísticas do carrossel

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#216]
baixar os dados de produção e fazer uma análise das estatísticas do carrossel para gerar um relatorio (em texto mesmo, não é pra desenvolver nada, apenas para ler os dados e interpretá-los).

Basicamente gravamos duas informações
. quando um item do carrossel é exibido (ou seja, quando o carrossel anda)
. quando um post é acessado a partir do carrossel (quando alguém clica no post a partir do carrossel)

* nota, não é computada a visualização do primeiro item do carrossel quando a página é carregada. conta só a partir do segundo. O que aparecer de visualização do primeiro item é pq o carrossel deu a volta toda e chegou ao primeiro.

O que queremos saber?

Frequencia de visualizações de cada item do carrossel
- [x] geral
- [x] por usuários logados
- [x] por editores / administradores

Frequencia de cliques em cada item do carrossel
- [x] geral
- [x] por usuarios logados
- [x] por editores / administradores

qual é o objetivo disso?

Ter dados concretos pra poder avaliar a efetividade do carrossel e podermos repensá-lo

**Comment by r-guimaraes** [comment]
[issue216rhs.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5970f41118eb59001f538600/125516c66e82c728ace21e0d46e187893687d1f8d9fbb750e611b2843b492d762a10e17132d0ba78bd102a075d5649aa13505944fcfd8c7ea2b33e24824e17ff933c0120996048e6edc00db513bb27814e80b6b58b4ec5ee3a23e38d895d73.zip)

**Comment by r-guimaraes** [comment]
Segue acima arquivos CSV com os resultados das pesquisas do Weryques, bem como gráficos detalhados dos dados levantados sobre o uso e click dos itens do carrossel

**Comment by r-guimaraes** [comment]
Editor    			 | ID
---------------------------
andre_editor 		 | 35432
dcmatielo 			 | 8967
deboraligieri 		 | 15009
Emilia Alves 		 | 398
Maria Luiza			 | 166
Política Humanização | 29809
Gustavo Nunes 		 | 122
Ricardo Teixeira 	 | 36
ricarte@usp.br		 | 6825


Administrador		 | ID
---------------------------
andre.benedito 		 | 9152
danimatielo			 | 3
Débora Aligieri 	 | 15009
Dalton 		 		 | 32
Fabiano				 | 36729
Leo					 | 31532
Mari  		 		 | 188
Patrícia		 	 | 9
rhs-admin			 | 1


- Ao relacionar os logs de views das estatísticas com os IDs dos editores e administradores do RHS, vemos que a maior parte dos cliques oriunda dos próprios editores.
- Confirmar afirmação acima observando arquivo: click_user_locado_with_id.csv (dentro do zip acima)
