### ISSUE TITLE
Remover domínio da blacklist do Hotmail

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#225]

**Comment by r-guimaraes** [comment]
Realizei novos testes hoje (de recuperação de senha) com um usuário do Hotmail, e parece estar ok.

O e-mail chegou normalmente na caixa de entrada

**Comment by fabianobn** [comment]
@r-guimaraes realizei os mesmos teste e o mesmo na primeira vez caiu na lixeira, porem depois de marcar que não era spam não caiu mais na lixeira.

**Comment by r-guimaraes** [comment]
Boa @fabianobn . Mais um ponto pra analisar nesse caso meio complicado

**Comment by MarianaSalles** [comment]
sensacional resolver isso!

**Comment by r-guimaraes** [comment]
\o//
