### ISSUE TITLE
verificar se posts criados via admin criam notificações

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#226]
verificar se quando cria um post pelo admin, e não pela interface da rhs, se dispara a notificação pra quem segue aquela pessoa

**Comment by fabianobn** [comment]
Os posts criados via painel de admin não criam notificações.

**Comment by leogermani** [comment]
O hook save_post é chamado toda vez q salva o post pelo admin, então vc precisa verificar se é realmente a primeira vez que vc está entrando aí pra só disparar o action de new_post uma vez.

sugestão: salvar um metadado informando q já foi disparado esse hook
