### ISSUE TITLE
botão visualizar post no painel não funciona

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#229]
quando clica no botão visualizar por no painel ele vai para uma página escrita não há post. o mesmo acontece quando clica no titulo do post no menu minhas postagens.

**Comment by leogermani** [comment]
Mari, vc se refere a posts que estão em rascunho?

**Comment by MarianaSalles** [comment]
sim.

2017-11-08 17:42 GMT-02:00 leogermani <notifications@github.com>:
