### ISSUE TITLE
post sem autoria - rever

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#231]
exemplos:

http://redehumanizasus.net/11509-neoliberalismo-e-impactos-na-saude/

http://redehumanizasus.net/210-homo-sapiens/

**Comment by MarianaSalles** [comment]
Carxs, vc podem verificar quantos posts sem autoria existem? Vcs acham que podemos resgatar o autor de algum backup do drupal 6. anterior a migração do drupal 7?

**Comment by MarianaSalles** [comment]
Acho que achamos.  Uns 1300 são posts de um tempo onde se podia postar sem autoria. uma opção que foi retirada da rede. E os outros são post de usuários que ao longo do tempo se descadastraram da rede, mas não apagaram seus posts. Por ora o mistério foi resolvido. E tirando o número total de posts publicados já sem autoria, esse número cai bastante. o que para 10 anos de rede fica razoável. To aqui pensando como encaminhar estes posts de autores que se foram, pensei em criar um usuário para isso, explicando que estes posts foram produzidos por usuários que saíram da rede, mas deixaram seu legado de publicações. que vcs acham?

**Comment by r-guimaraes** [comment]
Acho uma boa opção. Daí também poderia acrescentar um "Disclaimer" no início de cada um destes posts, informando que o autor aquele post se descadastrou da rede, e etc (E elaborarmos uma mensagem mais elaborada)

**Comment by r-guimaraes** [comment]
Verificar se os posts da categoria "Livro de Visitas" (cerca de 1300 posts) são ainda muito acessados.
Se não, serão ocultados de toda a interface pública da RHS.

Os posts de usuários "anônimos" serão migrados para um novo usuário, "RHS Legado"
