### ISSUE TITLE
Erro ao tentar atualizar Usuário Responsável pela categoria

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#237]
Erro ao tentar atualizar campo "Usuário Responsável" de algumas categorias de "contatos" (tickets)

**Comment by MarianaSalles** [comment]
já resolveu? vamos atualizar esse backlog?

**Comment by r-guimaraes** [comment]
Mari, resolvemos aquela questão em específico. Mas já identificamos que pode ocorrer novamente caso alguém crie 2 categorias com o mesmo slug. Por isso, vamos tentar alterar mais esse detalhe
