### ISSUE TITLE
Nova opção de busca

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#240]
Dar opção ao usuário se a busca deve retornar resultados contendo partes do termo da palavra-chave, ou apenas a palavra-chave completa

**Comment by MarianaSalles** [comment]
muito bom! vai ajudar, a saúde tem muitas siglas, procurar por exemplo ras que significa redes de atenção a saúde era impossível, pois ele achava dentro das palavras como rasteira, araras, aparas, etc.. rsrsrs Valeu! Mais uma!
