### ISSUE TITLE
E-mail de Nova Conta

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#242]
Não enviar a senha do usuário na notificação via e-mail de nova conta registrada

**Comment by r-guimaraes** [comment]
Na verdade o envio da senha foi configurado no painel admin do WordPress. Por padrão, a senha não é enviada para uma nova conta registrada. Portanto, retificar esta questão com admin/editores da rede

**Comment by pedronaves** [comment]
Rever também layout após acessar link para ativar conta
