### ISSUE TITLE
Erro no botão de compartilhamento de um post no Facebook

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#244]

**Comment by MarianaSalles** [comment]
Rodrigo vale investigar tb as imagens que vão em anexo. Além de dar página inexistente, ele leva opções bem malucas de imagens dos post. Sabemos que pela experiência que esse compartilhamento no facebook da de tempo sem tempos problemas. Temos contornado isso subindo imagens como anexo e mantendo o link. ;-)

**Comment by r-guimaraes** [comment]
Ainda não consegui reproduzir este erro. Tentei ontem a noite, e hoje durante o dia todo. 

Vou ver se  tem alguma instabilidade com o próprio share do Facebook

**Comment by r-guimaraes** [comment]
Embora não tenhamos alterado nada no código em relação a esta questão, creio que a dúvida foi sanada com a questão de compartilhar um post da fila de votação, e também o cache do facebook.

Deixando esta issue em validação para ainda deixar em observação
