### ISSUE TITLE
Criar box de Login

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#253]
Substituir a página de login por um "box", no qual o usuário clica e não sai da página onde está. Podendo fazer login de qualquer local da rede sem se perder no fluxo de navegação

**Comment by MarianaSalles** [comment]
Rodrigo ficou muito bom!  Notei uma coisa que vale considerar, se vc loga enquanto esta lendo um post ele te manda para a página principal. já eh bem melhor do que temos, mas será que da para ele manter a pessoa na pagina em que ela está?

**Comment by r-guimaraes** [comment]
Feito, Mari! Usuário mantém-se na mesma página que estava após o login!

**Comment by MarianaSalles** [comment]
Maravilha Rodrigo.
avisa  quando atualizar a versao atual!
bj
Mari



Em 20 de jan de 2018 17:48, "Rodrigo" <notifications@github.com> escreveu:
