### ISSUE TITLE
Responsividade dados view/share no post

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#256]
Melhorar a responsividade dos elementos de visualização e compartilhamento no post para tamanhos de tela menores

**Comment by r-guimaraes** [comment]
@fabianobn, ainda não ficou tão legal. Agora aquela parte do layout está quebrando das resoluções 420px até 990px. Dá uma revisada no media-query min/max width

**Comment by r-guimaraes** [comment]
Obs: testar sem estar logado

**Comment by r-guimaraes** [comment]
@fabianobn Muito bom!

**Comment by fabianobn** [comment]
Vlws :D
