### ISSUE TITLE
rever numero de compartilhamento em post na rede

### ISSUE THREAD

**Issue by MarianaSalles** [medialab-ufg/wp-rhs#258]
hoje do que eu notei aparece 0 em todos os posts da rede.

**Comment by r-guimaraes** [comment]
Mari, nestes casos talvez seja porque aqueles posts ainda não tenham sido compartilhados.
Clique para compartilhar algumas vezes via facebook/twitter, depois atualize a página para verificar

**Comment by MarianaSalles** [comment]
É vero rodrigo, mas ele computa apenas o compartilhado pelo nosso link no post.

**Comment by r-guimaraes** [comment]
Vamos utilizar os dados do Google Analytics. Integrar via API
