### ISSUE TITLE
Implementar ReCaptcha no Formulário de Contato

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#260]

**Comment by pedronaves** [comment]
@r-guimaraes implementei deixando o botão de submit desabilitado, ou seja, se inspecionarem o código e tirarem o "disabled", vai funcionar. 
Qual o nível de validação que precisamos pra esse contato?

**Comment by r-guimaraes** [comment]
Foi implementada validação do reCaptcha semelhante à página de registro

**Comment by MarianaSalles** [comment]
bacana! manda ver!
