### ISSUE TITLE
Logo comemorativa 10 anos

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#261]
Será utilizada por cerca de um ano na RHS, YouTube e capa Facebook

**Comment by pedronaves** [comment]
![rhs-10-anos.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598af6f2fb1a7b11ef52853d/125516c66e82c728ace21e0d46fa9c896ed3d3e48ee7b050e611b2843b492d762a10e17132d0ba78bd102a075d5649aa13505944fcfd8c7ea2b33e24824e17ff933c0120996048e6edc00db513bb27814e80b7b58c49c4ee3d27e08e8f5d73.png)

**Comment by fabianobn** [comment]
ficou show!

**Comment by r-guimaraes** [comment]
Estamos fazendo algumas adaptações para que a logo fique melhor na aplicação para o site
