### ISSUE TITLE
Visibilidade de acesso das Comunidades

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#262]
Exibir Link das comunidades no menu do site e do app apenas para usuários que estão em alguma comunidade

**Comment by MarianaSalles** [comment]
Essa issue seria importante para trabalharmos nas comunidade de professores e tb na do acolhesus. Quem está na comunidade pode ter acesso a suas comunidades pelo menu de usuário.  avaliar se isso demanda tecnicamente muitos ajustes nas comunidades.  e tb  para aproveitarmos todo o trabalho de criação desse espaço que por ora está pouco usado.

**Comment by MarianaSalles** [comment]
Muito bom! Fiz pequena observações aqui neste doc: https://docs.google.com/document/d/1O5XOyKxDjLi9piE-Ie3T9iZzmeyP6z7GMckJPIIMzeM/edit?usp=sharing
