### ISSUE TITLE
Aparecer para quem o post já foi indicado

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#268]

**Comment by MarianaSalles** [comment]
Rodrigo e André, tudo bem? Faço algumas obs e perguntas. 
 - Seria importante ter um autocompletar ao digitar nomes da rede, difícil saber como cada um colocou seu nome.  (será que fica muito trash por conta da quantidade?)
- Vale digitar e-mail ou só nome? 
- Vale digitar e-mail de alguém não cadastrado da rede? 
- Não vejo para quem já foi indicado os post que eu indiquei. fica visível só para o autor?
- Seria importante ficar visível a lista de para quem foi indicado para todos que acessem o post. 
obs: Se era isso, não consegui testar. indiquei posts na migração e não apareceu nem pra quem, nem uma confirmação se foi.

**Comment by MarianaSalles** [comment]
vi que o autocompletar já rola na plataforma atual. ;-)
