### ISSUE TITLE
Verificar usabilidade do box de login

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#273]
Reclamações que o box de login 'some' facilmente.

Testar também no internet explorer

**Comment by MarianaSalles** [comment]
Rodrigo, esse aqui tb ja rolou?

**Comment by r-guimaraes** [comment]
Essa, sim!

**Comment by MarianaSalles** [comment]
Rodrigo, tem novas reclamações sobre o box de login. Agora usuários reclamam que o box foge ao mouse e da erro ao clicar sobre o e-mail. algo anda passando com esse boxzinho, que será?  Vc pode verificar novamente? ;-)
