### ISSUE TITLE
Revisar botão "Limpar filtros" na busca

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#278]
Ideal seria se a funcionalidade "limpasse" também os filtros de GET na URL

**Comment by MarianaSalles** [comment]
Rodrigo, esse já foi certo?

**Comment by r-guimaraes** [comment]
Sobre essa questão, ficamos de avaliar se o "limpar filtros" deve limpar também todo o form quando o usuário já fez uma pesquisa com um ou mais filtros de busca. 

Daí no caso, 'limparia' tudo novamente.

**Comment by MarianaSalles** [comment]
seria delicado limpar um layer de cada vez, como um control z, mas acho que é luxo. avalie. (no mínimo seria bom limpar tudo). que vc acha?

**Comment by r-guimaraes** [comment]
Também acho que é um luxo. Facilita a vida do usuário que faz várias buscas bastante distintas "de uma vez", mas não ter essa funcionalidade não impede nem atrapalha nada no fluxo.
Então, numa escala de prioridade, essa seria uma issue que ficaria mais pro final da lista, né?
