### ISSUE TITLE
Exportar posts e usuários de uma vez

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#284]
Para facilitar o trabalho dos usuários da exportação da busca, e não precisar baixar vários arquivos

**Comment by MarianaSalles** [comment]
vou testar. esse já esta na rede ou só no homolog?

**Comment by MarianaSalles** [comment]
não exporta de uma vez. mas de 2500 vai bem. isso já resolve.  podemos considerar ok.
