### ISSUE TITLE
Tradução da ferramenta de imagem destacada

### ISSUE THREAD

**Issue by patrinutri** [medialab-ufg/wp-rhs#286]
Tradução da ferramenta de imagem destacada. Está sendo apresentada em inglês ao usuário.

**Comment by r-guimaraes** [comment]
@patrinutri bom dia! Obrigado pela contribuição mais uma vez!

Poderia enviar um print com a mensagem em inglês?

Revisei aqui no momento de publicar um novo post, mas não achei nada em inglês

Obrigado!

**Comment by patrinutri** [comment]
Olá Rodrigo,

Segue aí o print da tela da mensagem da ferramenta em inglês










2018-08-20 11:36 GMT-03:00 Rodrigo <notifications@github.com>:

**Comment by r-guimaraes** [comment]
Feito
