### ISSUE TITLE
Exibir número total de compartilhamento dos posts em redes sociais

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#293]
- [x] Facebook
- [x] Twitter

**Comment by MarianaSalles** [comment]
Rodrigo e André, nos posts onde o numero de visualizações e compartilhamentos é muito grande, passa dos 5 dígitos em um deles,  esta ficando confuso. vcs chegaram a ver um exemplo desses. posso buscar. mas vela separar um pouco para evitar essa sobre posição. Vale considerar um espaço de 6 dígitos para cada um desses números. o que é raro, mas quando acontece já fica resolvido. o que vcs acham?

**Comment by MarianaSalles** [comment]
Essa issue agora vi que ta dentro do painel. mas vale então abrir uma para olhar essa sobre posição no post normal mesmo. vou fazer. desculpa a confusão.
