### ISSUE TITLE
Informação sobre quem votou no post (quando foi publicado)

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/wp-rhs#297]
Discutir se é uma boa questão pra dar ainda mais transparência na rede

**Comment by MarianaSalles** [comment]
Tb acho, quanto mais transparência maior o engajamento. Mas vale antes checar com toda equipe sobre essa aposta na votação. Como não é like, vale pensar junto um pouco mais. Vou levar para equipe e volto rápido! fiz comentários sobre isso tb aqui: https://docs.google.com/document/d/1O5XOyKxDjLi9piE-Ie3T9iZzmeyP6z7GMckJPIIMzeM/edit?usp=sharing
