### ISSUE TITLE
Melhorar captação de dados direto da rede

### ISSUE THREAD

**Issue by eduardo2s** [medialab-ufg/wp-rhs#301]
A ferramenta de coleta de dados que se encontra na rede, traz os dados sobre os posts, mas o número de comentários apresentado por post vem com valores errados. Além disso implementar uma coluna na planilha gerada com o ID do post, seria bastante útil para aqueles que fazem pesquisas sobre a rede e utilizam o banco de dados como auxilio.

**Comment by r-guimaraes** [comment]
ID do posts já gerados com a planilha de exportação
