### ISSUE TITLE
Fazer URLs de filtro por estado e municípios funcionarem

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#31]
Vamos fazer essa aqui juntos, usando rewrite_rules e pre_get_posts

**Comment by leogermani** [comment]
Esse template será o mesmo usado no resultado de busca.

Haverá uma aba para posts e uma para usuários. Dentro de cada aba uma caixa com filtros e ordenação.

No caso da busca e do filtro por cidades, os filtrs já virão preenchidos.

![IMG_20170816_165453.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5385ea5febef97b1f959fde8/125516c66e82c728ace21e0d46c1b9bd1cd0d3f8d8b9e712f262a1c27c1272206b48e13b628ae92dbc56395b4d5a47ac135a5e12fef08e2df4be3a708a580eb8d5685d20ce2f0dbefad341eb5ee779c11ac7a4b6984fc2ee3e2fe68e8f4d3719011c8ef85f32a08b06.jpg)

**Comment by fabianobn** [comment]
Validar o template criado na issue #43, qualquer modificação só avisar !!
