### ISSUE TITLE
comentários pendentes

### ISSUE THREAD

**Issue by patrinutri** [medialab-ufg/wp-rhs#311]
Quando acesso o painel aparece comentários pendentes, mas quando vou fazer a aprovação eles não parecem mais

**Comment by patrinutri** [comment]
Mandei prints por email para Rodrigo com a situação retratada

**Comment by r-guimaraes** [comment]
@andre2ar favor verificar também

**Comment by r-guimaraes** [comment]
Feito

**Comment by patrinutri** [comment]
Valeu Rodrigo!
Obrigada 🙏 

Enviado do meu iPhone

Em 20 de nov de 2018, à(s) 11:35, Rodrigo <notifications@github.com> escreveu:
