### ISSUE TITLE
Formulário de Contato

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/wp-rhs#44]
Demanda detalhamento

**Comment by leogermani** [comment]
Formulário de Contato

Hoje cai em um gmail

você preenche
Nome
Email 
Assunto
Mensagem
Estado e cidade

Em vez de ir para um gmail, ir para um administrador.

principais assuntos
. técnicos
. sobre a politica de humanização
. desaparecimento de pessoas, pedido de ajuda pra marcar consulta...
. dúvidas sobre a Rede, ajuda pra postar, buscando materiais...

Gostaríamos

. identificar se é usuário logado ou não
. escolher o assunto a partir de uma lista
. encaminhar a resposta para a pessoa adequada. (editores ou equipe técnica)

Queremos um lugar onde possamos responder todas as mensagens juntas e separá-las por assunto.

**Comment by leogermani** [comment]
Requisitos:



. Formulário no front end com os campos

Nome
email
assunto
estado cidade 
mensagem

. Se o usuário tiver logado, só assunto e mensagem.

. Esse formulário não precisa ser personalizável no admin.

. A lista de assuntos pode ser personalizável pelo admin.
.. Cada assunto pode ter um nome e um email relacionado

. Quando alguém envia um contato, vai por email para o email do assunto.

. No admin, os editores e adminstradores podem:

.. responder as mensagens
... as respostas vão por email pro cara que mandou o contato
... se o usuário tiver logado, fica o historico de bate papo, tipo um ticket?
.. marcar como resolvidas (ver quais status precisa)
.. encaminhar as mensagens para algum email

. Fazer checagem de permissão específica current_user_can('manage_contact_forms')

**Comment by MarianaSalles** [comment]
Leo mandei no seu email, mas aqui entre as paginas 101 e 115 tem o estudo que falei do formulário de contato. tb uma modelagem, de como poderia ser, com mais algumas funcionalidades, que talvez vale debater.  a que mais me chamou atenção, foi a possibilidade de debater entre os editores a resposta antes dela ser encaminhada. e da poder filtrar por editor, assunto, e data. ai vai o link do relatório: https://drive.google.com/file/d/0BwjE7YdlqgQuMmZPNG9kLUJRbGM/view?usp=sharing

**Comment by fabianobn** [comment]
- [x] Pegar data de cadastro do usuario no contato.

- [x] Categoria não está pegando ao enviar o contato
