### ISSUE TITLE
Estrutura das Comunidades

### ISSUE THREAD

**Issue by fabianobn** [medialab-ufg/wp-rhs#70]

**Comment by fabianobn** [comment]
1. Estrutura

**Taxonomia**: Comunidade
**Term**: ComunidadeN
**Term_Meta**:
 * Desc
 * Foto
 * Gerentes
 * ...
 * ...
 * Participantes
 * Owner
 * Total
   * Participantes
   * Posts

2. Regras

**Gerenciador**
* Editar Descrição
* Participantes
   * Adicionar
   * Excluir 
* Definir Outros Gerentes

**Super Gerenciador**
* Gerentes
* Não pode ser destituído

**Comment by willavelar** [comment]
- [x]  Tela de membros
- [x]  Inserção de membro pelo moderador
- [x]  Testar interação dos botões na listagem
- [x]  Fazer a pagina da comunidade ser o template taxonomy-comunidades
- [x]  Fazer um pre_get_post para adicionar o status private na query, se o usuário tiver permissão ou se a comunidade for aberta.
- [x]  Retirar informação dos Seguidores
- [x]  Configurar imagem inserir/editar
- [x]  Quando publicar poder escolher entre publico e dentro da comunidade, sendo que apenas dentro da comunidade ela será com o status private.
Ao publicar um post vai ter a opção "Publicar em:" e uma lista de checkboxes com as comunidades que o usuário faz parte e mais uma primeira opção "Público RHS")
.. Se o usuário não participar de nenhuma comunidade, pode ocultar isso e ter um input hidden com o Publico como padrão
.. na hora de publicar o post verificar:
... se ele está marcado como Publico, seu status será public, mesmo que também vá ser adicionado em comunidades
... se não estiver marcado como Público, seu status será private, mesmo que esteja apenas dentro de uma comunidade aberta

**Comment by fabianobn** [comment]
![Captura de tela de 2017-08-04 15-25-17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590b2971e5b99b00203f4eda/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f27c3dd5bb65ef163b505a424ca95c595856e0ebc969f9ec6923ce4e01ffd4645f26c43c47aeb18519ed09bc208b4b80e3b88f4e94e02f39f5c9de116a415841c3aa1f27aa8b48c952f74ee14c5da3123760e574327a55d9.png)

Esta comunidade apareceu para mim, sem eu ter criada nenhuma!
