### ISSUE TITLE
Importação dos Posts - Fazer Considerar Fila de Votação

### ISSUE THREAD

**Issue by fabianobn** [medialab-ufg/wp-rhs#76]
Ao importar os Posts ver como funciona os Votos no Drupal para ser implementado em nosso sistema de Votos dos Posts.

**Comment by leogermani** [comment]
Fazer a importação:

Aparentemente, no drupal é só pela contagem dos votos mesmo. Então é fazer um update pra ver quem tem mais de 5 e marcar como aprovado.

**Comment by leogermani** [comment]
Considerar também a idade do post. Apenas posts com até duas semanas ficam na fila. Posts com mais de duas semanas e menos de 5 votos vão praquele outro status de quem não foi promovido

**Comment by leogermani** [comment]
CORRIGIR: Tem que ser post >= 5 ou > 4 ... e não > 5
